### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by Zumbalamambo** [electech6/ORBSLAM2_detailed_comments#1]
Is it possible to run this in ubuntu?

**Comment by electech6** [comment]
Yes

**Comment by Zumbalamambo** [comment]
@electech6 thank you! how did you create a dense point cloud? Is it created using orb slam (monocular)?

**Comment by electech6** [comment]
> @electech6 thank you! how did you create a dense point cloud? Is it created using orb slam (monocular)?
Original ORB-SLAM2 did not provide the code with dense point clouds.  However, you can make it by yourself in RGBD mode. 
Here are some useful jobs for you. 
1, ORBSLAM2_with_pointcloud_map
https://github.com/gaoxiang12/ORBSLAM2_with_pointcloud_map
2, ORB-SLAM2_RGBD_DENSE_MAP,modified from Xiang Gao's "ORB_SLAM2_modified".It is added a dense loopclosing map model
https://github.com/tiantiandabaojian/ORB-SLAM2_RGBD_DENSE_MAP
