### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by xujiahuan** [electech6/ORBSLAM2_detailed_comments#2]
I've found that  if you make comments here, the program get bugs in the codes.

> Location
![sendpix0](https://user-images.githubusercontent.com/22728324/89988689-7ac14f80-dcb2-11ea-8bda-822bd0a971f5.jpg)
:ORBexatractor.cc/computeOrbDescriptor

 #define GET_VALUE(idx) \
        center[cvRound(pattern[idx].x*b + pattern[idx].y*a)*step + \        // y'* step     <——Here
               cvRound(pattern[idx].x*a - pattern[idx].y*b)]                // x'

**Comment by electech6** [comment]
fixed already, thanks!
